# Generated by Django 2.0 on 2019-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='cpu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
