# Generated by Django 2.0 on 2019-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltapi', '0002_auto_20190614_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='offencommand',
            name='command_result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offencommand',
            name='exec_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offencommand',
            name='hostnames',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
