# Generated by Django 2.0 on 2019-06-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saltapi', '0004_servergroup_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servergroup',
            old_name='remark',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='userpriv',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='group_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saltapi.ServerGroup'),
        ),
    ]
